vestat/calendario/urls.py
# -*- encoding: utf-8 -*-
from django.conf.urls.defaults import *

from views import EventsCalendarView

urlpatterns = patterns('',
     url(r'^(\d{4})/(\d{2})/$', EventsCalendarView.as_view(), name="events_calendar"),
)

vestat/urls.py
# -*- encoding: utf-8 -*-
from django.conf.urls.defaults import *
from django.contrib import admin

import vestat.caixa.urls
import vestat.relatorios.urls
import vestat.config.urls
import vestat.calendario.urls

import views
from vestat.settings import MEDIA_ROOT, STATIC_ROOT
from vestat import temp

temp.clear()

# Uncomment the next two lines to enable the admin:
#from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    # (r'^vestat/', include('vestat.foo.urls')),

     (r'^admin/', include(admin.site.urls)),
     (r'^$', views.index),
     (r'^caixa/', include(vestat.caixa.urls)),
     (r'^config/', include(vestat.config.urls)),
     (r'^relatorios/', include(vestat.relatorios.urls)),
     (r'^calendario/', include(vestat.calendario.urls, namespace="calendario")),
     (r'^m/(?P<path>.*)$', 'django.views.static.serve',
             {'document_root': MEDIA_ROOT}),
     (r'^static/(?P<path>.*)$', 'django.views.static.serve',
             {'document_root': STATIC_ROOT}),
)

handler500 = 'views.server_error'

vestat/templates/barra_topo.html
<nav id="barra-topo">
    <ul id="menu">
        <li class="nome-aplicacao">{{ project_settings.NOME_APLICACAO }}</li>
        <li><a href="/caixa/">Caixa</a></li>
        <li><a href="/relatorios/">Relatórios</a></li>
        <li>
            <a href="{% url 'calendario:events_calendar' agora|date:"Y" agora|date:"m" %}">
                Calendário
            </a>
        </li>
        <li><a href="/config/vestat/">Configurações</a></li>
    </ul>
</nav>

vestat/templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link rel="stylesheet" type="text/css" href="/m/css/blueprint/screen.css" media="screen, projection"/>
    <link rel="stylesheet" type="text/css" href="/m/css/blueprint/print.css" media="print"/>
    <!--[if lt IE 8]>
      <link rel="stylesheet" href="/m/css/blueprint/ie.css" type="text/css" media="screen, projection">
    <![endif]-->
    {% block head %}
    <link rel="stylesheet" type="text/css" href="/m/css/vestat.css" media="screen, projection"/>
    <link rel="stylesheet" type="text/css" href="/m/css/barra_topo.css" media="screen, projection"/>
    <link rel="stylesheet" type="text/css" href="/m/css/vestat_print.css" media="print"/>
    {% endblock %}
    <title>{{ title }}</title>
  </head>

  <body>
    {% block body %}
    {% include "barra_topo.html" %}
    <div id="vestat" class="container">
        <div class="span-24 title">
            {% block title %}
            <h1>{{ title }}</h1>
            {% endblock title %}
        </div>

        <div class="span-24 content">
            {% if messages %}
                {% for message in messages %}
                    <div class="box{% if message.tags %} {{ message.tags }}{% endif %}">
                        {{ message|safe }}
                    </div>
                {% endfor %}
            {% endif %}
            {% block content %}
            {% endblock content %}
        </div>
    </div>
  {% endblock body %}
  </body>
</html>

vestat/templates/base_wide.html
{% extends "base.html" %}
{% block body %}
{% include "barra_topo.html" %}
<div id="vestat" class="wide">
    <div class="title">
        {% block title %}
        <h1>{{ title }}</h1>
        {% endblock title %}
    </div>

    <div class="content">
        {% if messages %}
            {% for message in messages %}
                <div class="box{% if message.tags %} {{ message.tags }}{% endif %}">
                    {{ message|safe }}
                </div>
            {% endfor %}
        {% endif %}
        {% block content %}
        {% endblock content %}
    </div>
</div>
{% endblock body %}

vestat/templates/data.html
{% load vestat_extras %}
<span id="clock">&nbsp;</span>
<h1>
    <a class="botao" href="/caixa/{{ data|ontem|date:"Y/m/d" }}" title="{{ data|ontem }}">&lt;</a>
    <a href="#" title="Mudar dia" id="mudar_dia">Dia: {{ data|date:"d/m/Y" }}</a>
    <a class="botao" href="/caixa/{{ data|amanha|date:"Y/m/d" }}" title="{{ data|amanha }}">&gt;</a>
</h1>

vestat/templates/index.html
{% extends "base.html" %}
{% block content %}
    <h2><a href="caixa/">Caixa</a></h2>
    <p>Registra vendas, despesas de caixa e movimentações bancárias.</p>
    <hr />

    <h2><a href="relatorios/">Relatórios</a></h2>
    <p>Gera relatórios sobre os dados registrados.</p>
    <hr />

    <h2><a href="config/">Configurações</a></h2>
    <p>Edita configurações do programa.</p>
    <hr />
{% endblock %}