vestat/caixa/urls.py
# -*- encoding: utf-8 -*-
from django.conf.urls.defaults import *

urlpatterns = patterns('vestat.caixa.views',
     (r'^$', 'index'),

     (r'^(?P<ano>\d{4})/(?P<mes>\d{2})/(?P<dia>\d{2})/$', 'ver_dia'),
     (r'^(?P<ano>\d{4})/(?P<mes>\d{2})/(?P<dia>\d{2})/criar$', 'criar_dia'),
     (r'^(?P<ano>\d{4})/(?P<mes>\d{2})/(?P<dia>\d{2})/remover$', 'remover_dia'),
     
     (r'^(?P<ano>\d{4})/(?P<mes>\d{2})/(?P<dia>\d{2})/imprimir$', 'imprimir_dia'),

     (r'^(?P<ano>\d{4})/(?P<mes>\d{2})/(?P<dia>\d{2})/anotacoes$', 'anotacoes'),

     (r'^(?P<ano>\d{4})/(?P<mes>\d{2})/(?P<dia>\d{2})/venda/adicionar$', 'adicionar_venda'),
     (r'^(?P<ano>\d{4})/(?P<mes>\d{2})/(?P<dia>\d{2})/venda/(?P<id>\d+)/entrada$', 'editar_venda_entrada'),
     (r'^(?P<ano>\d{4})/(?P<mes>\d{2})/(?P<dia>\d{2})/venda/(?P<id>\d+)/saida$', 'editar_venda_saida'),
     (r'^(?P<ano>\d{4})/(?P<mes>\d{2})/(?P<dia>\d{2})/venda/(?P<id>\d+)/abrir$', 'abrir_venda'),
     (r'^(\d{4})/(\d{2})/(\d{2})/venda/(?P<id>\d+)/remover$', 'remover_venda'),
     (r'^(\d{4})/(\d{2})/(\d{2})/venda/(?P<venda_id>\d+)/cartao/(?P<cartao_id>\d+)/remover$', 'remover_cartao'),

     (r'^(?P<ano>\d{4})/(?P<mes>\d{2})/(?P<dia>\d{2})/despesa/adicionar$', 'adicionar_despesa'),
     (r'^(\d{4})/(\d{2})/(\d{2})/despesa/(?P<id>\d+)/remover$', 'remover_despesa'),
     
     (r'^(?P<ano>\d{4})/(?P<mes>\d{2})/(?P<dia>\d{2})/ajuste/adicionar$', 'adicionar_ajuste'),
     (r'^(\d{4})/(\d{2})/(\d{2})/ajuste/(?P<id>\d+)/remover$', 'remover_ajuste'),

     (r'^(?P<ano>\d{4})/(?P<mes>\d{2})/(?P<dia>\d{2})/movbancaria/adicionar$', 'adicionar_movbancaria'),
     (r'^(\d{4})/(\d{2})/(\d{2})/movbancaria/(?P<id>\d+)/remover$', 'remover_movbancaria'),
)

vestat/urls.py
# -*- encoding: utf-8 -*-
from django.conf.urls.defaults import *
from django.contrib import admin

import vestat.caixa.urls
import vestat.relatorios.urls
import vestat.config.urls
import vestat.calendario.urls

import views
from vestat.settings import MEDIA_ROOT, STATIC_ROOT
from vestat import temp

temp.clear()

# Uncomment the next two lines to enable the admin:
#from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    # (r'^vestat/', include('vestat.foo.urls')),

     (r'^admin/', include(admin.site.urls)),
     (r'^$', views.index),
     (r'^caixa/', include(vestat.caixa.urls)),
     (r'^config/', include(vestat.config.urls)),
     (r'^relatorios/', include(vestat.relatorios.urls)),
     (r'^calendario/', include(vestat.calendario.urls, namespace="calendario")),
     (r'^m/(?P<path>.*)$', 'django.views.static.serve',
             {'document_root': MEDIA_ROOT}),
     (r'^static/(?P<path>.*)$', 'django.views.static.serve',
             {'document_root': STATIC_ROOT}),
)

handler500 = 'views.server_error'

vestat/contabil/models.py
# -*- encoding: utf-8 -*-
"""
Modelos de um registro de contabilidade.

Contas
======

A hierarquia de contas é criada conforme vão sendo adicionados
lançamentos.

Cada conta é criada quando é referenciada pela primeira vez.

O nome da conta deve estar no formato `conta:subconta:subconta...`, onde
cada subconta é separada de sua conta-mãe pelo símbolo definido na
variável `contabil.SEPARADOR_DE_CONTAS` (nesse exemplo, dois-pontos).

"""

import datetime
from decimal import Decimal

from django.db import models
from django.core.exceptions import ValidationError

from vestat.config import config_pages, Link
from django.core.urlresolvers import reverse_lazy

class Registro(models.Model):
    nome = models.TextField(unique=True)

    def __unicode__(self):
        return self.nome

    def balanco(self, conta, de=None, ateh=None):
        """
        Calcula o balanço financeiro de uma conta dentro de um intervalo
        de datas dadas, inclusive.

        Argumentos:

        - conta: um nome de conta seguindo o formato descrito no módulo.
        - de: a data inicial; um objeto `datetime.date`
        - ateh: a data final; um objeto `datetime.date`
        """

        filtros = {}

        if de:
            assert isinstance(de, datetime.date)
            filtros["data__gte"] = de

        if ateh:
            assert isinstance(ateh, datetime.date)
            filtros["data__lte"] = ateh

        resultado = Decimal('0')
        transacoes = self.transacoes.filter(**filtros)

        for transacao in transacoes:
            for lancamento in transacao.lancamentos.all():
                if lancamento.conta == conta:
                    resultado += lancamento.valor

        return resultado

class Transacao(models.Model):
    registro = models.ForeignKey(Registro, related_name="transacoes")
    data = models.DateField("Data")
    descricao = models.TextField(blank=True)

    class Meta:
        verbose_name = "Transação"
        verbose_name_plural = "Transações"
        ordering = ["-data"]

    def __unicode__(self):
        return u"{data} - {descricao}".format(**vars(self))

    @property
    def eh_consistente(self):
        """
        `True` se os lançamentos da transação somam zero, `False` se não.

        """

        return sum(t.valor for t in self.lancamentos.all()) == 0

    def save(self, *args, **kwargs):
        super(Transacao, self).save(*args, **kwargs)


class Lancamento(models.Model):
    transacao = models.ForeignKey(Transacao, related_name="lancamentos")
    valor = models.DecimalField("Valor", max_digits=10, decimal_places=2)
    conta = models.TextField()

    class Meta:
        verbose_name = "Lançamento"
        ordering = ["-transacao"]

    def __unicode__(self):
        return u"{conta}: {valor}".format(**vars(self))

    def save(self, *args, **kwargs):
        if self.conta == "":
            raise ValidationError("Campo 'conta' não pode estar vazio!")

        super(Lancamento, self).save(*args, **kwargs)


config_pages["vestat"].add(
    Link(
        "transacoes-de-contabilidade",
        "Transações de contabilidade",
        reverse_lazy("admin:contabil_transacao_changelist"),
        "Adicionar/remover/editar"
    ),
)

vestat/caixa/views.py
# -*- encoding: utf-8 -*-
import datetime

from django.shortcuts import redirect, render_to_response, get_object_or_404
from django.db.models import Sum, Avg, Count
from django.template import RequestContext
from django.http import HttpResponseRedirect
from django.utils.safestring import mark_safe
from django.conf import settings
from django.contrib import messages

from models import *
from forms import *

def index(request):
    """Índice da webapp. Redireciona pro dia adequado."""

    agora = datetime.datetime.now()
    um_dia = datetime.timedelta(1)

    if agora.hour < 6: # é madrugada, contar como dia anterior
        agora -= um_dia

    return HttpResponseRedirect("/caixa/%04d/%02d/%02d" % (agora.year, agora.month, agora.day))

def criar_dia(request, ano, mes, dia):
    data = datetime.date(int(ano), int(mes), int(dia))

    try:
        dia = Dia.objects.get(data=data)
    except Dia.DoesNotExist:
        dia = Dia(data=data)
        dia.save()

    return redirect(dia)

def remover_dia(request, ano, mes, dia):
    data = datetime.date(int(ano), int(mes), int(dia))
    dia = get_object_or_404(Dia, data=data)
    dia.delete()
    return redirect(dia)

def anotacoes(request, ano, mes, dia):
    data = datetime.date(*map(int, [ano, mes, dia]))
    dia = get_object_or_404(Dia, data=data)
    form_anotacoes = AnotacoesForm(instance=dia)

    if request.method == 'POST':
        form_anotacoes = AnotacoesForm(request.POST, instance=dia)
        if form_anotacoes.is_valid():
            form_anotacoes.save()
            return redirect(dia)

    return render_to_response('caixa/anotacoes.html', {
                              'title': "Dia: %s" % (dia.data,),
                              'dia': dia,
                              'data': data,
                              'form_anotacoes': form_anotacoes,
                              'movbancarias': dia.movimentacaobancaria_set.filter(pgto_cartao__isnull=True),
                              'taxas_cartao': dia.movimentacaobancaria_set.filter(pgto_cartao__isnull=False).\
                                  aggregate(Sum('valor'))['valor__sum'],
                              'voltar_link': '/',
                              'voltar_label': 'Módulos',
                             },
                             context_instance=RequestContext(request))


def adicionar_venda(request, ano, mes, dia):
    data = datetime.date(*map(int, [ano, mes, dia]))
    dia = get_object_or_404(Dia, data=data)
    form_venda = AbrirVendaForm()

    if request.method == 'POST':
        form_venda = AbrirVendaForm(request.POST)
        if form_venda.is_valid():
            venda = form_venda.save(commit=False)
            venda.dia = dia
            venda.save()
            return redirect(dia)

    return render_to_response('caixa/adicionar_venda.html', {
                              'title': "Dia: %s" % (dia.data,),
                              'dia': dia,
                              'data': data,
                              'form_venda': form_venda,
                              'movbancarias': dia.movimentacaobancaria_set.filter(pgto_cartao__isnull=True),
                              'taxas_cartao': dia.movimentacaobancaria_set.filter(pgto_cartao__isnull=False).\
                                  aggregate(Sum('valor'))['valor__sum'],
                              'voltar_link': '/',
                              'voltar_label': 'Módulos',
                             },
                             context_instance=RequestContext(request))

def editar_venda_entrada(request, ano, mes, dia, id):
    data = datetime.date(*map(int, [ano, mes, dia]))
    dia = get_object_or_404(Dia, data=data)
    venda = get_object_or_404(Venda, id=id)
    form_venda = AbrirVendaForm(instance=venda)

    if request.method == 'POST':
        form_venda = AbrirVendaForm(request.POST, instance=venda)
        if form_venda.is_valid():
            venda = form_venda.save()
            return redirect(dia)

    return render_to_response('caixa/adicionar_venda.html', {
                              'title': "Dia: %s" % (dia.data,),
                              'dia': dia,
                              'data': data,
                              'form_venda': form_venda,
                              'movbancarias': dia.movimentacaobancaria_set.filter(pgto_cartao__isnull=True),
                              'taxas_cartao': dia.movimentacaobancaria_set.filter(pgto_cartao__isnull=False).\
                                  aggregate(Sum('valor'))['valor__sum'],
                              'voltar_link': '/',
                              'voltar_label': 'Módulos',
                             },
                             context_instance=RequestContext(request))

def editar_venda_saida(request, ano, mes, dia, id):
    data = datetime.date(*map(int, [ano, mes, dia]))
    dia = get_object_or_404(Dia, data=data)
    venda = get_object_or_404(Venda, id=id)
    form_fechar_venda = FecharVendaForm(instance=venda)
    pgtos_cartao = venda.pagamentocomcartao_set.all()
    if pgtos_cartao is None: pgtos_cartao = []
    form_cartao = PagamentoComCartaoForm()
    erro = None

    if request.method == 'POST':
        if 'adicionar_pgto_cartao' in request.POST:
            form_fechar_venda = FecharVendaForm(request.POST, instance=venda)
            form_cartao = PagamentoComCartaoForm(request.POST)
            if form_cartao.is_valid():
                pgto_cartao = form_cartao.save(commit=False)
                pgto_cartao.venda = venda
                venda.pagamentocomcartao_set.add(pgto_cartao)
                venda.save()
            if form_fechar_venda.is_valid():
                venda = form_fechar_venda.save()
        elif 'fechar_venda' in request.POST:
            form_fechar_venda = FecharVendaForm(request.POST, instance=venda)
            if form_fechar_venda.is_valid():
                venda = form_fechar_venda.save()
                pgtos = [venda.pgto_dinheiro, venda.pgto_cheque, venda.pagamentocomcartao_set.aggregate(Sum('valor'))['valor__sum']]
                pgto_total = sum(filter(None, pgtos))
                if pgto_total == venda.conta:
                    venda.fechar()
                    venda.save()
                    return redirect(dia)
                else:
                    erro = mark_safe("Total da conta (<strong>%.2f</strong>) <strong>≠</strong> total de pagamentos (<strong>%.2f</strong>)" % (venda.conta, pgto_total))
        elif 'salvar_venda' in request.POST:
            form_fechar_venda = FecharVendaForm(request.POST, instance=venda)
            if form_fechar_venda.is_valid():
                venda = form_fechar_venda.save()
                venda.save()
                return redirect(venda.get_absolute_url() + "saida")

    return render_to_response('caixa/fechar_venda.html', {
                              'title': "Dia: %s" % (dia.data,),
                              'dia': dia,
                              'data': data,
                              'form_fechar_venda': form_fechar_venda,
                              'pgtos_cartao': pgtos_cartao,
                              'form_cartao': form_cartao,
                              'erro': erro,
                              'movbancarias': dia.movimentacaobancaria_set.filter(pgto_cartao__isnull=True),
                              'taxas_cartao': dia.movimentacaobancaria_set.filter(pgto_cartao__isnull=False).\
                                  aggregate(Sum('valor'))['valor__sum'],
                              'voltar_link': '/',
                              'voltar_label': 'Módulos',
                             },
                             context_instance=RequestContext(request))

def editar_venda(request, ano, mes, dia, id):
    data = datetime.date(*map(int, [ano, mes, dia]))
    dia = get_object_or_404(Dia, data=data)
    venda = get_object_or_404(Venda, id=id)
    form_venda = VendaForm(instance=venda)
    pgtos_cartao = venda.pagamentocomcartao_set.all()
    if pgtos_cartao is None: pgtos_cartao = []
    form_cartao = PagamentoComCartaoForm()
    erro = None

    if request.method == 'POST':
        if 'adicionar_pgto_cartao' in request.POST:
            form_venda = VendaForm(request.POST, instance=venda)
            form_cartao = PagamentoComCartaoForm(request.POST)
            if form_cartao.is_valid():
                pgto_cartao = form_cartao.save(commit=False)
                pgto_cartao.venda = venda
                venda.pagamentocomcartao_set.add(pgto_cartao)
                venda.save()
        else:
            form_venda = VendaForm(request.POST, instance=venda)
            if form_venda.is_valid():
                venda = form_venda.save()
                pgtos = [venda.pgto_dinheiro, venda.pgto_cheque, venda.pagamentocomcartao_set.aggregate(Sum('valor'))['valor__sum']]
                pgto_total = sum(filter(None, pgtos))
                if pgto_total == venda.conta:
                    venda.fechar()
                    venda.save()
                    return redirect(dia)
                else:
                    erro = mark_safe("Total da conta (<strong>%.2f</strong>) <strong>≠</strong> total de pagamentos (<strong>%.2f</strong>)" % (venda.conta, pgto_total))
    return render_to_response('caixa/editar_venda.html', {
                              'title': "Dia: %s" % (dia.data,),
                              'dia': dia,
                              'data': data,
                              'form_venda': form_venda,
                              'erro': erro,
                              'pgtos_cartao': pgtos_cartao,
                              'form_cartao': form_cartao,
                              'movbancarias': dia.movimentacaobancaria_set.filter(pgto_cartao__isnull=True),
                              'taxas_cartao': dia.movimentacaobancaria_set.filter(pgto_cartao__isnull=False).\
                                  aggregate(Sum('valor'))['valor__sum'],

vestat/templates/caixa/adicionar_ajuste.html
{% extends "caixa/ver_dia.html" %}

{% block javascript %}
    <script type="text/javascript" src="/m/js/autofocus.js"></script>
    <script type="text/javascript" src="/m/js/jquery.maskMoney.js"></script>
    <script type="text/javascript" src="/m/js/dinheiro.js"></script>
{% endblock %}

{% block form %}
        <form id="adicionar_ajuste" class="info" name="adicionar_ajuste_form" action="" method="POST">
            <a href="{{ dia.get_absolute_url }}" title="Fechar" class="fechar">x</a>
            <h3>Nova ajuste</h3>
            <span id="valor" class="dinheiro{% if form_ajuste.valor.errors %} error{% endif %}">
                {{ form_ajuste.valor.label_tag }} {{ form_ajuste.valor }}
            </span>
            <span id="categoria"{% if form_ajuste.categoria.errors %} class="error"{% endif %}>
                {{ form_ajuste.categoria.label_tag }} {{ form_ajuste.categoria }}
            </span>
            <span id="descricao"{% if form_ajuste.descricao.errors %} class="error"{% endif %}>
                {{ form_ajuste.descricao.label_tag }} {{ form_ajuste.descricao }}
            </span>
            <input type="submit" name="adicionar_ajuste" value="Adicionar" />
        </form>
{% endblock %}

vestat/templates/caixa/adicionar_despesa.html
{% extends "caixa/ver_dia.html" %}

{% block javascript %}
    <script type="text/javascript" src="/m/js/autofocus.js"></script>
    <script type="text/javascript" src="/m/js/jquery.maskMoney.js"></script>
    <script type="text/javascript" src="/m/js/dinheiro.js"></script>
{% endblock %}

{% block form %}
        <form id="adicionar_despesa" class="info" name="adicionar_despesa_form" action="" method="POST">
            <a href="{{ dia.get_absolute_url }}" title="Fechar" class="fechar">x</a>
            <h3>Nova Despesa</h3>
            <span id="valor" class="dinheiro{% if form_despesa.valor.errors %} error{% endif %}">
                {{ form_despesa.valor.label_tag }} {{ form_despesa.valor }}
            </span>
            <span id="categoria"{% if form_despesa.categoria.errors %} class="error"{% endif %}>
                {{ form_despesa.categoria.label_tag }} {{ form_despesa.categoria }}
            </span>
            <input type="submit" name="adicionar_despesa" value="Adicionar" />
        </form>
{% endblock %}

vestat/templates/caixa/adicionar_movbancaria.html
{% extends "caixa/ver_dia.html" %}

{% block javascript %}
    <script type="text/javascript" src="/m/js/autofocus.js"></script>
    <script type="text/javascript" src="/m/js/jquery.maskMoney.js"></script>
    <script type="text/javascript" src="/m/js/dinheiro.js"></script>
{% endblock %}

{% block form %}
        <form id="adicionar_movbancaria" class="info" name="adicionar_movbancaria_form" action="" method="POST">
            <a href="{{ dia.get_absolute_url }}" title="Fechar" class="fechar">x</a>
            <h3>Nova Mov. Bancária</h3>
            <span id="valor" class="dinheiro{% if form_movbancaria.valor.errors %} error{% endif %}">
                {{ form_movbancaria.valor.label_tag }} {{ form_movbancaria.valor }}
            </span>
            <span id="categoria"{% if form_movbancaria.categoria.errors %} class="error"{% endif %}>
                {{ form_movbancaria.categoria.label_tag }} {{ form_movbancaria.categoria }}
            </span>
            <input type="submit" name="adicionar_movbancaria" value="Adicionar" />
        </form>
{% endblock %}

vestat/templates/caixa/adicionar_venda.html
{% extends "caixa/ver_dia.html" %}

{% block javascript %}
    <script type="text/javascript" src="/m/js/autofocus.js"></script>
    <script type="text/javascript" src="/m/js/adicionar_venda.js"></script>
{% endblock %}

{% block form %}
        <form id="adicionar_venda" class="info" name="adicionar_venda_form" action="" method="POST">
            <a href="{{ dia.get_absolute_url }}" title="Fechar" class="fechar">x</a>
            <h3>Nova Venda</h3>
            <span id="mesa"{% if form_venda.mesa.errors %} class="error"{% endif %}>
                {{ form_venda.mesa.label_tag }} {{ form_venda.mesa }}
            </span>
            <span id="hora_entrada"{% if form_venda.hora_entrada.errors %} class="error"{% endif %}>
                {{ form_venda.hora_entrada.label_tag }} {{ form_venda.hora_entrada }}
            </span>
            <span id="num_pessoas"{% if form_venda.num_pessoas.errors %} class="error"{% endif %}>
                {{ form_venda.num_pessoas.label_tag }} {{ form_venda.num_pessoas }}
            </span>
            <span id="categoria"{% if form_venda.categoria.errors %} class="error"{% endif %}>
                    {{ form_venda.categoria.label_tag }} {{ form_venda.categoria }}
            </span>
            <span id="cidade_de_origem"{% if form_venda.cidade_de_origem.errors %} class="error"{% endif %}>
                {{ form_venda.cidade_de_origem.label_tag }} {{ form_venda.cidade_de_origem }}
            </span>
            <span id="pousada_que_indicou"{% if form_venda.pousada_que_indicou.errors %} class="error"{% endif %}>
                {{ form_venda.pousada_que_indicou.label_tag }} {{ form_venda.pousada_que_indicou }}
            </span>
            <br />
            <input type="submit" name="adicionar_venda" value="Adicionar" />
        </form>
{% endblock %}

vestat/templates/caixa/anotacoes.html
{% extends "caixa/ver_dia.html" %}

{% block javascript %}
    <script type="text/javascript" src="/m/js/autofocus_textarea.js"></script>
{% endblock %}

{% block anotacoes %}
        <form id="anotacoes" class="notice" name="anotacoes_form" action="" method="POST">
            {{ form_anotacoes.anotacoes }}
            {{ form_anotacoes.errors }}
            <p>Pra remover, salve a anotação em branco.</p>
            <input type="submit" name="salvar_anotacoes" value="Salvar" />
            <input type="reset" value="Limpar" />
        </form>
{% endblock %}

vestat/templates/caixa/base.html
{% extends "base.html" %}

vestat/templates/caixa/criar_dia.html
{% extends "caixa/base.html" %}

{% block head %}
    {{ block.super }}
    <script type="text/javascript" src="/m/js/jquery.js"></script>
    <script type="text/javascript" src="/m/js/clock.js"></script>
    <script type="text/javascript" src="/m/js/mudar_dia.js"></script>
    <title>Dia: {{ data }}</title>
{% endblock %}

{% block title %}
    {% include "data.html" %}
{% endblock %}

{% block content %}
<a id="criar_dia" href="criar">Criar dia de trabalho</a>
{% endblock %}

vestat/templates/caixa/editar_venda.html
{% extends "caixa/ver_dia.html" %}
{% load vestat_extras %}

{% block javascript %}
    <script type="text/javascript" src="/m/js/autofocus.js"></script>
    <script type="text/javascript" src="/m/js/jquery.maskMoney.js"></script>
    <script type="text/javascript" src="/m/js/dinheiro.js"></script>
{% endblock %}

{% block form %}
        {% if erro %}
            <div class="error">{{ erro }}</div>
        {% endif %}
        <form id="editar_venda" class="info" name="editar_venda_form" action="" method="POST">
            <a href="{{ dia.get_absolute_url }}" title="Fechar" class="fechar">x</a>

            <h3>Editar Venda</h3>

            <span id="mesa"{% if form_venda.mesa.errors %} class="error"{% endif %}>
                {{ form_venda.mesa.label_tag }} {{ form_venda.mesa }}
            </span>
            <span id="hora_entrada"{% if form_venda.hora_entrada.errors %} class="error"{% endif %}>
                <label for="id_hora_entrada">Entrada</label> {{ form_venda.hora_entrada|default:"00:00"|time:"H:i" }}
            </span>
            <span id="num_pessoas"{% if form_venda.num_pessoas.errors %} class="error"{% endif %}>
                {{ form_venda.num_pessoas.label_tag }} {{ form_venda.num_pessoas }}
            </span>
            <span id="categoria"{% if form_venda.categoria.errors %} class="error"{% endif %}>
                    {{ form_venda.categoria.label_tag }} {{ form_venda.categoria }}
            </span>
            <span id="cidade_de_origem"{% if form_venda.cidade_de_origem.errors %} class="error"{% endif %}>
                {{ form_venda.cidade_de_origem.label_tag }} {{ form_venda.cidade_de_origem }}
            </span>
            <span id="pousada_que_indicou"{% if form_venda.pousada_que_indicou.errors %} class="error"{% endif %}>
                {{ form_venda.pousada_que_indicou.label_tag }} {{ form_venda.pousada_que_indicou }}
            </span>

            <br />

            <span id="hora_saida"{% if form_venda.hora_saida.errors %} class="error"{% endif %}>
                {{ form_venda.hora_saida.label_tag }} {{ form_venda.hora_saida }}
            </span>
            <span id="conta" class="dinheiro{% if form_venda.conta.errors %} error{% endif %}">
                <label for="id_conta">Entrada</label> {{ form_venda.conta }}
            </span>
            <span id="gorjeta"{% if form_venda.gorjeta.errors %} class="error"{% endif %}>
                {{ form_venda.gorjeta.label_tag }} {{ form_venda.gorjeta }}
            </span>
            <span id="pgto_dinheiro" class="dinheiro{% if form_venda.pgto_dinheiro.errors %} error{% endif %}">
                    {{ form_venda.pgto_dinheiro.label_tag }} {{ form_venda.pgto_dinheiro}}
            </span>
            <span id="pgto_cheque" class="dinheiro{% if form_venda.pgto_cheque.errors %} error{% endif %}">
                {{ form_venda.pgto_cheque.label_tag }} {{ form_venda.pgto_cheque }}
            </span>

            <p><input type="submit" name="editar_venda" value="Salvar" /></p>

            {% if pgtos_cartao %}
                <table id="pgtos_cartao" class="tablesorter">
                <caption>Pagamentos com Cartão</caption>
                <tbody>
                {% for pgto_cartao in pgtos_cartao %}
                    <tr>
                        <td>{{ pgto_cartao.valor|colorir_num }}</td>
                        <td>{{ pgto_cartao.bandeira }}</td>
                        <td><a href="{{ pgto_cartao.get_absolute_url }}remover">Remover</a></td>
                    </tr>
                {% endfor %}
                </tbody>
                <tfoot>
                    <tr>
                        <td>{{ form_cartao.valor }}</td>
                        <td>{{ form_cartao.bandeira }}</td>
                        <td><input type="submit" name="adicionar_pgto_cartao" value="Adicionar" /></td>
                    </tr>
                </tfoot>
                </table>
            {% endif %}
        </form>
{% endblock %}